export const mockVolunteer = {
  id: "1",
  name: "Sarah Johnson",
  email: "sarah.johnson@email.com",
  role: "Medical",
  assignedArea: "Dagon Township",
  contact: "+95 9 123 456 789",
  reportsSubmitted: 5,
  groupsJoined: 2,
  avatar: "/volunteer-profile-photo.jpg",
}

export const reliefCenters = [
  {
    id: "1",
    name: "Yangon Central Shelter",
    type: "Shelter",
    status: "Available",
    distance: "2.3 km",
    lat: 16.8661,
    lng: 96.1951,
    contact: "+95 1 234 567",
    capacity: 500,
    currentOccupancy: 320,
  },
  {
    id: "2",
    name: "Medical Emergency Center",
    type: "Medical",
    status: "Available",
    distance: "1.8 km",
    lat: 16.8555,
    lng: 96.1974,
    contact: "+95 1 234 568",
    capacity: 200,
    currentOccupancy: 150,
  },
  {
    id: "3",
    name: "Food Distribution Hub",
    type: "Food",
    status: "Full",
    distance: "3.1 km",
    lat: 16.8732,
    lng: 96.185,
    contact: "+95 1 234 569",
    capacity: 300,
    currentOccupancy: 300,
  },
  {
    id: "4",
    name: "North District Relief Point",
    type: "Shelter",
    status: "Available",
    distance: "4.5 km",
    lat: 16.89,
    lng: 96.205,
    contact: "+95 1 234 570",
    capacity: 400,
    currentOccupancy: 200,
  },
]

export const volunteerGroups = [
  {
    id: "1",
    name: "Rescue Team A",
    task: "Medical Aid",
    members: 12,
    zone: "Dagon Township",
    status: "Active",
    leader: "Dr. Aung Soe",
    contact: "+95 9 222 333 444",
  },
  {
    id: "2",
    name: "Logistics Division B",
    task: "Supply Distribution",
    members: 8,
    zone: "Bahan Township",
    status: "In Transit",
    leader: "Kyaw Lin",
    contact: "+95 9 222 333 445",
  },
  {
    id: "3",
    name: "Water & Sanitation Team",
    task: "Emergency Services",
    members: 15,
    zone: "South Okkalapa",
    status: "Active",
    leader: "Soe Moe",
    contact: "+95 9 222 333 446",
  },
  {
    id: "4",
    name: "Community Support Network",
    task: "Counseling & Support",
    members: 6,
    zone: "Kamaryut",
    status: "Completed",
    leader: "Ma Thida",
    contact: "+95 9 222 333 447",
  },
]

export const supplies = [
  {
    id: "1",
    item: "Water Bottles",
    quantity: 250,
    center: "Yangon Central Shelter",
    category: "Food",
    icon: "Droplet",
  },
  {
    id: "2",
    item: "Medical Kits",
    quantity: 45,
    center: "Medical Emergency Center",
    category: "Medical",
    icon: "Heart",
  },
  { id: "3", item: "Canned Food", quantity: 500, center: "Food Distribution Hub", category: "Food", icon: "Package" },
  { id: "4", item: "Blankets", quantity: 120, center: "Yangon Central Shelter", category: "Shelter", icon: "Home" },
  {
    id: "5",
    item: "First Aid Supplies",
    quantity: 30,
    center: "Medical Emergency Center",
    category: "Medical",
    icon: "Heart",
  },
  {
    id: "6",
    item: "Tools & Equipment",
    quantity: 25,
    center: "North District Relief Point",
    category: "Tools",
    icon: "Wrench",
  },
]

export const reports = [
  {
    id: "1",
    reporter: "Aung Kyaw",
    category: "Damage",
    description: "Major structural damage to residential buildings in Ward 3",
    location: "Dagon Township",
    urgency: "High",
    status: "Verified",
    timestamp: new Date("2025-11-10T10:30:00"),
  },
  {
    id: "2",
    reporter: "Khin May",
    category: "Supply Needs",
    description: "Urgent need for drinking water and food supplies",
    location: "Bahan Township",
    urgency: "High",
    status: "Pending",
    timestamp: new Date("2025-11-10T11:15:00"),
  },
  {
    id: "3",
    reporter: "Zaw Moe",
    category: "Medical",
    description: "Multiple casualties requiring emergency medical attention",
    location: "South Okkalapa",
    urgency: "Critical",
    status: "Verified",
    timestamp: new Date("2025-11-10T08:45:00"),
  },
]

export const announcements = [
  {
    id: "1",
    type: "Alert",
    title: "Heavy Rainfall Expected",
    content: "Volunteers in areas prone to flooding should prepare for evacuation procedures.",
    author: "Admin",
    timestamp: new Date("2025-11-10T14:00:00"),
  },
  {
    id: "2",
    type: "Update",
    title: "New Shelter Opened",
    content: "North District Relief Point is now accepting residents. Capacity: 400 people.",
    author: "Coordinator - Soe",
    timestamp: new Date("2025-11-10T12:30:00"),
  },
  {
    id: "3",
    type: "Request",
    title: "Medical Volunteers Needed",
    content: "We are urgently seeking medical professionals for the Emergency Medical Center.",
    author: "Dr. Aung Soe",
    timestamp: new Date("2025-11-10T11:00:00"),
  },
]
