export const mockVolunteer = {
  id: "1",
  name: "Sarah Johnson",
  email: "sarah.johnson@email.com",
  role: "Medical",
  assignedArea: "Dagon Township",
  contact: "+95 9 123 456 789",
  reportsSubmitted: 5,
  groupsJoined: 2,
  avatar: "/volunteer-profile-photo.jpg",
}

export const reliefCenters = [
  {
    id: "1",
    name: "Yangon Central Shelter",
    type: "Shelter",
    status: "Available",
    distance: "2.3 km",
    lat: 16.8661,
    lng: 96.1951,
    contact: "+95 1 234 567",
    capacity: 500,
    currentOccupancy: 320,
  },
  {
    id: "2",
    name: "Medical Emergency Center",
    type: "Medical",
    status: "Available",
    distance: "1.8 km",
    lat: 16.8555,
    lng: 96.1974,
    contact: "+95 1 234 568",
    capacity: 200,
    currentOccupancy: 150,
  },
  {
    id: "3",
    name: "Food Distribution Hub",
    type: "Food",
    status: "Full",
    distance: "3.1 km",
    lat: 16.8732,
    lng: 96.185,
    contact: "+95 1 234 569",
    capacity: 300,
    currentOccupancy: 300,
  },
  {
    id: "4",
    name: "North District Relief Point",
    type: "Shelter",
    status: "Available",
    distance: "4.5 km",
    lat: 16.89,
    lng: 96.205,
    contact: "+95 1 234 570",
    capacity: 400,
    currentOccupancy: 200,
  },
]

export const volunteerGroups = [
  {
    id: "1",
    name: "Rescue Team A",
    task: "Medical Aid",
    members: 12,
    zone: "Dagon Township",
    status: "Active",
    leader: "Dr. Aung Soe",
    contact: "+95 9 222 333 444",
  },
  {
    id: "2",
    name: "Logistics Division B",
    task: "Supply Distribution",
    members: 8,
    zone: "Bahan Township",
    status: "In Transit",
    leader: "Kyaw Lin",
    contact: "+95 9 222 333 445",
  },
  {
    id: "3",
    name: "Water & Sanitation Team",
    task: "Emergency Services",
    members: 15,
    zone: "South Okkalapa",
    status: "Active",
    leader: "Soe Moe",
    contact: "+95 9 222 333 446",
  },
  {
    id: "4",
    name: "Community Support Network",
    task: "Counseling & Support",
    members: 6,
    zone: "Kamaryut",
    status: "Completed",
    leader: "Ma Thida",
    contact: "+95 9 222 333 447",
  },
]

export const supplies = [
  {
    id: "1",
    item: "Water Bottles",
    quantity: 250,
    center: "Yangon Central Shelter",
    category: "Food",
    icon: "Droplet",
  },
  {
    id: "2",
    item: "Medical Kits",
    quantity: 45,
    center: "Medical Emergency Center",
    category: "Medical",
    icon: "Heart",
  },
  { id: "3", item: "Canned Food", quantity: 500, center: "Food Distribution Hub", category: "Food", icon: "Package" },
  { id: "4", item: "Blankets", quantity: 120, center: "Yangon Central Shelter", category: "Shelter", icon: "Home" },
  {
    id: "5",
    item: "First Aid Supplies",
    quantity: 30,
    center: "Medical Emergency Center",
    category: "Medical",
    icon: "Heart",
  },
  {
    id: "6",
    item: "Tools & Equipment",
    quantity: 25,
    center: "North District Relief Point",
    category: "Tools",
    icon: "Wrench",
  },
]

export const reports = [
  {
    id: "1",
    reporter: "Aung Kyaw",
    category: "Damage",
    description: "Major structural damage to residential buildings in Ward 3",
    location: "Dagon Township",
    urgency: "High",
    status: "Verified",
    timestamp: new Date("2025-11-10T10:30:00"),
  },
  {
    id: "2",
    reporter: "Khin May",
    category: "Supply Needs",
    description: "Urgent need for drinking water and food supplies",
    location: "Bahan Township",
    urgency: "High",
    status: "Pending",
    timestamp: new Date("2025-11-10T11:15:00"),
  },
  {
    id: "3",
    reporter: "Zaw Moe",
    category: "Medical",
    description: "Multiple casualties requiring emergency medical attention",
    location: "South Okkalapa",
    urgency: "Critical",
    status: "Verified",
    timestamp: new Date("2025-11-10T08:45:00"),
  },
]

export const announcements = [
  {
    id: "1",
    type: "Alert",
    title: "Heavy Rainfall Expected",
    content: "Volunteers in areas prone to flooding should prepare for evacuation procedures.",
    author: "Admin",
    timestamp: new Date("2025-11-10T14:00:00"),
  },
  {
    id: "2",
    type: "Update",
    title: "New Shelter Opened",
    content: "North District Relief Point is now accepting residents. Capacity: 400 people.",
    author: "Coordinator - Soe",
    timestamp: new Date("2025-11-10T12:30:00"),
  },
  {
    id: "3",
    type: "Request",
    title: "Medical Volunteers Needed",
    content: "We are urgently seeking medical professionals for the Emergency Medical Center.",
    author: "Dr. Aung Soe",
    timestamp: new Date("2025-11-10T11:00:00"),
  },
]

export const disasterSafetyGuides = [
  {
    id: "1",
    type: "Earthquake",
    icon: "AlertTriangle",
    color: "#FF6B6B",
    description: "Strong ground shaking and structural damage",
    beforeSteps: [
      "Secure heavy furniture to walls",
      "Identify safe spots (under tables, against interior walls)",
      "Keep emergency supplies ready",
      "Know how to turn off utilities",
      "Practice drop, cover, and hold on",
    ],
    duringSteps: [
      "DROP, COVER, and HOLD ON immediately",
      "Stay where you are until shaking stops",
      "If outdoors, move away from buildings and power lines",
      "If driving, pull over safely and stay in vehicle",
      "Do not use elevators",
    ],
    afterSteps: [
      "Check for injuries and provide first aid",
      "Inspect home for damage",
      "Be prepared for aftershocks",
      "Use emergency exits if evacuation needed",
      "Listen to emergency broadcasts",
    ],
    emergencyContacts: ["911 for emergency", "Local disaster management office"],
  },
  {
    id: "2",
    type: "Flood",
    icon: "Waves",
    color: "#4ECDC4",
    description: "Rising water levels and water-related hazards",
    beforeSteps: [
      "Know evacuation routes and shelters",
      "Store important documents in waterproof containers",
      "Have emergency supplies at higher elevation",
      "Know location of high ground",
      "Sign up for emergency alerts",
    ],
    duringSteps: [
      "Move to high ground immediately",
      "Do not attempt to cross flooded roads",
      "Turn off utilities if instructed",
      "Stay indoors away from windows",
      "Follow evacuation orders",
    ],
    afterSteps: [
      "Return home only when authorities say safe",
      "Document damage with photos for insurance",
      "Boil water before drinking unless advised otherwise",
      "Avoid floodwaters (may contain contaminants)",
      "Check on neighbors and vulnerable persons",
    ],
    emergencyContacts: ["911 for emergency", "Local flood management agency"],
  },
  {
    id: "3",
    type: "Hurricane/Typhoon",
    icon: "Wind",
    color: "#95E1D3",
    description: "High winds, heavy rain, and storm surge",
    beforeSteps: [
      "Board up windows and doors",
      "Trim tree branches near home",
      "Secure outdoor objects",
      "Stock up on supplies for 2 weeks",
      "Prepare evacuation plan",
    ],
    duringSteps: [
      "Stay indoors in the strongest part of building",
      "Go to interior room on lowest floor",
      "Stay away from windows and doors",
      "Do not go outside even briefly",
      "Listen to emergency updates",
    ],
    afterSteps: [
      "Wait for all-clear before leaving shelter",
      "Watch for hazards (downed power lines, debris)",
      "Wear protective equipment when cleaning",
      "Properly dispose of hazardous materials",
      "Check on neighbors and community",
    ],
    emergencyContacts: ["911 for emergency", "Hurricane hotline"],
  },
  {
    id: "4",
    type: "Wildfire",
    icon: "Flame",
    color: "#FF8C42",
    description: "Rapid spread of fire with smoke and ash",
    beforeSteps: [
      "Create defensible space around home",
      "Clear gutters and remove dead vegetation",
      "Have evacuation bags ready",
      "Know multiple evacuation routes",
      "Keep vehicle fueled to at least half tank",
    ],
    duringSteps: [
      "Evacuate immediately if ordered",
      "Close all windows and doors",
      "Turn on exterior lights",
      "Leave garage doors open",
      "Don't lock doors to aid firefighters",
    ],
    afterSteps: [
      "Return home only when authorities permit",
      "Stay alert for hot spots and embers",
      "Wear protective equipment when cleaning",
      "Properly dispose of hazardous materials",
      "Check on neighbors and community",
    ],
    emergencyContacts: ["911 for emergency", "Local fire department"],
  },
  {
    id: "5",
    type: "Landslide",
    icon: "Mountain",
    color: "#A8D8EA",
    description: "Sudden movement of earth and rock",
    beforeSteps: [
      "Know if you live on or near a slope",
      "Maintain drainage systems",
      "Have evacuation plan ready",
      "Monitor weather closely",
      "Keep emergency supplies prepared",
    ],
    duringSteps: [
      "Evacuate immediately if warned",
      "Move away from the slope",
      "Go to higher ground if possible",
      "Avoid valleys and canyons",
      "Listen to emergency broadcasts",
    ],
    afterSteps: [
      "Check for debris-blocked roads",
      "Report hazards to authorities",
      "Help neighbors if safe to do so",
      "Document damage carefully",
      "Check for gas/water line damage",
    ],
    emergencyContacts: ["911 for emergency", "Local geological survey"],
  },
]

export const helpRequestPosts = [
  {
    id: "1",
    groupName: "Rescue Team A",
    groupId: "1",
    title: "Need urgent first aid kits and bandages",
    category: "Medical Aid",
    description:
      "We are running critically low on medical supplies at Dagon Township shelter. We have over 150 people in need of medical attention. Please respond ASAP.",
    location: "Dagon Township",
    urgency: "High",
    status: "Needs Help",
    image: "/medical-supplies-still-life.png",
    timestamp: new Date("2025-11-10T14:25:00"),
    comments: [
      {
        id: "c1",
        userName: "Volunteer - Kyaw",
        message: "We can deliver medical kits from Medical Emergency Center in 30 minutes.",
        timestamp: new Date("2025-11-10T14:45:00"),
      },
      {
        id: "c2",
        userName: "Dr. Aung Soe",
        message: "Great! Please prioritize sterile bandages and antiseptic solutions.",
        timestamp: new Date("2025-11-10T15:00:00"),
      },
    ],
  },
  {
    id: "2",
    groupName: "Logistics Division B",
    groupId: "2",
    title: "Request for food supply distribution - 500 meals needed",
    category: "Supply Need",
    description:
      "Food Distribution Hub is organizing meal distribution for 500 people in Bahan Township. Need volunteers to help pack and deliver.",
    location: "Bahan Township",
    urgency: "Medium",
    status: "Needs Help",
    image: "/food-supplies.jpg",
    timestamp: new Date("2025-11-10T13:00:00"),
    comments: [
      {
        id: "c3",
        userName: "Volunteer - Soe Moe",
        message: "We can send 5 volunteers from Water & Sanitation Team.",
        timestamp: new Date("2025-11-10T13:30:00"),
      },
    ],
  },
  {
    id: "3",
    groupName: "Water & Sanitation Team",
    groupId: "3",
    title: "Looking for donation of bottled water - 1000 bottles",
    category: "Donation Request",
    description:
      "Urgent request for bottled water to support South Okkalapa relief zone. Clean water supply is critical for sanitation.",
    location: "South Okkalapa",
    urgency: "High",
    status: "Needs Help",
    image: "/assorted-water-bottles.png",
    timestamp: new Date("2025-11-10T12:15:00"),
    comments: [],
  },
  {
    id: "4",
    groupName: "Community Support Network",
    groupId: "4",
    title: "Volunteer support needed for counseling sessions",
    category: "Volunteer Support",
    description:
      "We need additional counselors and support staff for mental health counseling sessions. Training provided.",
    location: "Kamaryut",
    urgency: "Low",
    status: "Completed",
    image: "/community-support.jpg",
    timestamp: new Date("2025-11-10T10:00:00"),
    comments: [
      {
        id: "c4",
        userName: "Ma Thida",
        message: "We found 8 counselors to help. Mission accomplished!",
        timestamp: new Date("2025-11-10T11:30:00"),
      },
    ],
  },
  {
    id: "5",
    groupName: "Rescue Team A",
    groupId: "1",
    title: "Emergency logistics support for evacuation",
    category: "Logistics",
    description:
      "Need transportation vehicles for evacuation of 200 people from flood-prone areas. Immediate assistance required.",
    location: "Dagon Township",
    urgency: "Critical",
    status: "Needs Help",
    image: "/emergency-evacuation.jpg",
    timestamp: new Date("2025-11-10T09:45:00"),
    comments: [],
  },
]
